### ISSUE TITLE
Dynamically set token `scale`

### ISSUE THREAD

**Issue by ryanio** [solui/solui#3]
Love the project so far 🙂

I am writing my first solUI for [FixedRate.sol](https://github.com/ryanio/FixedRate.sol) and it's been a great experience. One request I have is to be able to dynamically set the token `scale`, since in my case it depends on the ERC20s specified in the contract.

It would be great if I could specify it somehow like: `{ scale: '@input[token1.decimals()]' }`

Otherwise, it's looking good!

![127 0 0 1_3001_](https://user-images.githubusercontent.com/22116/73328453-aac16d80-420e-11ea-9e6b-c9ba76e1df73.png)

In my case I would also like to nest panels under others, so first you would enter an exchange's contract address to query it, and then you could see the functions you can execute based on the result. It would give an opportunity to define more experiences.

I would also use a conditional `if` feature to show or hide a panel depending on if a property is a certain value.

For security I would like for users to be assured that an instance of a contract they are interacting with is genuine and untampered with by comparing `codeHash`.

---

Thanks for all your work on this project! It definitely feels like a futuristic way of defining dapp UIs.

Below are some other ideas/suggestions I thought of while prototyping:

1. inputs
   1. dropdown true/false for bools
   1. `default` value
   1. `description` field for inputs that require a bit more explanation
   1. html input placeholder to better suggest the expected type
      1. right now always shows `text` for me
1. identicons for addresses, validate onChange
   1. perhaps check out [react-ens-addresses](https://github.com/ensdomains/react-ens-address) to kill 2 birds with 1 stone
1. Optional step after deploy to verify contract on Etherscan
   1. would be 🔥
1. `messageAfterDeploySuccess` for giving further instructions to the user after a successful deploy.
   1. in my case for example "Exchange contract deployed! Now add liquidity by sending an amount of token2 (and token1 if bilateral) to the contract."
1. `@solui/cli` local build cmd
   1. so i can create an action to publish my solui to gh pages on updates to master

**Comment by hiddentao** [comment]
Wow, so many great suggestions! I'm going to setup a Roadmap project and add these issues to it. I think it's best to track them individually.

Regarding the scale, yeah, that would be a great feature. I deliberately didn't go far with the initial feature set because I was waiting for feedback like yours. Best to aim at building what most people need rather than just what I think is needed ;)

* The `codeHash` comparision is a great idea. I think it could be added as a validation -> https://github.com/solui/solui/issues/7.
* Post-deploy verification on etherscan - doesn't that require source code though? because the solUI publishing process doesn't include that. But there is a plan to have eventually integrate with etherscan in another manner, see https://github.com/solui/solui/issues/5
* Sub-panels - I did initially have the idea of "groups of panels" wherein there were group-level inputs but the UX turned out to be a bit confusing, mainly because if you have, say, 5 panels within a group then it's easy to miss out on the fact that the bottom panel cannot be executed until you fill in the group-level input by scrolling back up. It's a UI issue. Conceptually I agree with you that since panels can share data (e.g. contract address) it makes sense to group them somehow. Still thinking about this. On the other hand multi-step panels are on the roadmap -> https://github.com/solui/solui/issues/6
* Conditional inputs are a good idea -> https://github.com/solui/solui/issues/8
* Basic inputs enhancments -> https://github.com/solui/solui/issues/9, https://github.com/solui/solui/issues/10
* Address input enhancements -> https://github.com/solui/solui/issues/11, https://github.com/solui/solui/issues/12
* `messageAfterDeploySuccess` - I like it -> https://github.com/solui/solui/issues/13

**Comment by hiddentao** [comment]
Regarding the `@solui/cli` local build command do you mean being able to publish the entire thing to github pages? 

This would mean the solUI renderer package would be need to be hosted on your github pages along with your Dapp JSON spec (since I'm not sure if Temporal IPFS gateway supports CORS requests) and would mean your UI isn't "decentralized".

**Comment by ryanio** [comment]
> Wow, so many great suggestions! I'm going to setup a Roadmap project and add these issues to it. I think it's best to track them individually. 

Thanks, and sounds great -  the newly opened issues look 💯 :)

**Comment by hiddentao** [comment]
Just realized default field value is already supported, just forgot to document it :)  Use the `initialValue` key. Will update docs soon.

**Comment by ryanio** [comment]
closing this for now, thanks for all your hard work!
